PersonalBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    # apps urls
    path('accounts/', include('user_accounts.urls')),
    path('user-panel/', include('user_panel.urls')),
    path('posts/', include('post.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
    # django and third-party app urls
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index_page'),
    path('', views.HomePageView.as_view(), name='contact-form-view'),
]

user_panel/urls.py
from django.urls import path
from .views import DashboardView, EditProfileView, ChangePasswordView

app_name = "user_panel"
urlpatterns = [
    path('dashbord', DashboardView.as_view(), name="dashboard"),
    path('change-password', ChangePasswordView.as_view(), name="change-password"),
    path('edit-info', EditProfileView.as_view(), name="edit-info"),
]

user_panel/models.py
from django.db import models

# Create your models here.

user_panel/forms.py
from django.core import validators
from django import forms
from user_accounts.models import User

extensions = [x.lower() for x in validators.get_available_image_extensions()]


class EditProfileModelForm(forms.ModelForm):
    avatar = forms.ImageField(
        widget=forms.FileInput(),
        validators=[
            validators.FileExtensionValidator(allowed_extensions=extensions)
        ]
    )
    username = forms.CharField(
        label="Username",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control-lg",
                "placeholder": "Username",
            }
        ),
        validators=[
            validators.MaxLengthValidator(50),
            validators.ProhibitNullCharactersValidator]
    )
    first_name = forms.CharField(
        label="First name",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control-lg",
                "placeholder": "First Name",
            }
        ),
        validators=[validators.MaxLengthValidator(100),
                    validators.ProhibitNullCharactersValidator]

    )
    last_name = forms.CharField(
        label="Last name",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control-lg",
                "placeholder": "First Name",
            }
        ),
        validators=[validators.MaxLengthValidator(100),
                    validators.ProhibitNullCharactersValidator]
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'avatar',)


class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        label="Current password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "placeholder": "Your Current Password", }
        ),
        validators=[
            validators.MinLengthValidator(8),
        ]
    )
    password = forms.CharField(
        label="New Password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "placeholder": "Your New Password", }
        ),
        validators=[
            validators.MinLengthValidator(8),
        ]
    )

    confirm_password = forms.CharField(
        label="Confirm New Password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "placeholder": "Confirm Your Password",
        }
        ),
        validators=[
            validators.MinLengthValidator(8),
        ]
    )


    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password == confirm_password:
            return confirm_password
        raise ValidationError('Passwords do not match')

user_panel/views.py
from django.contrib import messages
from django.views.generic.base import TemplateView, View
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, reverse,render
from user_accounts.models import User
from .forms import EditProfileModelForm, ChangePasswordForm
from django.contrib.auth import logout
from tools.send_email_tool import send_email
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class DashboardView(TemplateView):
    template_name = "user_panel/dashboard.html"


@method_decorator(login_required, name='dispatch')
class EditProfileView(SuccessMessageMixin, View):
    def get(self, request):
        this_user_id = request.user.id
        retrieved_user = User.objects.filter(id=this_user_id).first()
        edit_profile_form = EditProfileModelForm(instance=retrieved_user)
        context = {
            "form": edit_profile_form,
            "user": retrieved_user
        }
        return render(request, 'user_panel/edit_info.html', context)

    def post(self, request):
        this_user_id = request.user.id
        retrieved_user = User.objects.filter(id=this_user_id).first()
        edit_profile_form = EditProfileModelForm(request.POST, request.FILES, instance=retrieved_user)
        if edit_profile_form.is_valid():
            edit_profile_form.save()
            messages.success(request, 'Your profile was successfully updated.')
            return redirect(f"{self.request.path}#dashboardPartial")
        context = {
            "form": edit_profile_form,
            "user": retrieved_user
        }
        return render(request, 'user_panel/edit_info.html', context)


@method_decorator(login_required, name='dispatch')
class ChangePasswordView(View):
    
    def get(self, request):
        change_password_form = ChangePasswordForm()
        context = {
            "form":  change_password_form
        }
        return render(request, 'user_panel/change_password.html', context)
    
    def post(self, request):
        change_password_form = ChangePasswordForm(request.POST)
        if change_password_form.is_valid():
            user = User.objects.filter(id=request.user.id).first()
            current_password = change_password_form.cleaned_data.get('current_password')
            password = change_password_form.cleaned_data.get('confirm_password')
            if user.check_password(current_password):
                user.set_password(password)
                logout(request)
                messages.success(request, 'Your password was successfully updated.')
                send_email(
                    subject="Your password has changed",
                    to=user.email,
                    context={'user': user},
                    template_name='mail_templates/password_changed.html'
                )
                return redirect(reverse('accounts:login'))
            else:
                change_password_form.add_error('password', 'Password is not correct')
        context = {
            "form": change_password_form
        }        
        return render(request, 'user_panel/change_password.html', context)


@method_decorator(login_required, name='dispatch')
class DashboardViewPartial(TemplateView):
    template_name = "user_panel/components/dashboard_component.html"

user_panel/templates/user_panel/change_password.html
{% extends 'main/_layout.html' %}
{% load render_partial %}
{% load thumbnail %}
{% load static %}

{% block title %}
    Change Password
{% endblock %}

{% block content %}
    <div class="container">
            {% include 'user_panel/components/messages.html' %}
            <div class="row">
                <div class="col-md-4" id="dashboardPartial">
                    {% render_partial 'user_panel.views.DashboardViewPartial' %}
                </div>
                <div class="col-md-8">
                <form class="form-floating form-md" action="{% url 'user_panel:change-password' %}" method="POST">
                    <div class="container-fluid">
                        {% csrf_token %}
                        {{ form.current_password.label }}
                        <div class="mb-3">
                            {{ form.current_password }}
                        </div>
                        {{ form.password.label }}
                        <div class="mb-3">
                            {{ form.password }}
                        </div>
                        {{ form.confirm_password.label }}
                        <div class="mb-3">
                            {{ form.confirm_password }}
                        </div>
                        {% if form.errors %}
                            <ul>
                                <li class="alert alert-danger">{{ form.errors }}</li>
                            </ul>
                        {% endif %}
                        <button type="submit" class="btn btn-primary">Edit Information</button>
                        <div class="contact-mf"></div>
                </form>
            </div>
    </div>
    </div>
{% endblock %}

user_panel/templates/user_panel/dashboard.html
{% extends 'main/_layout.html' %}
{% load render_partial %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">

            {% include 'user_panel/components/messages.html' %}
            <div class="col-md-8">
                <div class="col-md-4">
                    {% render_partial 'user_panel.views.DashboardViewPartial' %}
                </div>
            </div>
        </div>
        <div class="contact-mf"></div>
    </div>
{% endblock %}

user_panel/templates/user_panel/edit_info.html
{% extends 'main/_layout.html' %}
{% load render_partial %}
{% load thumbnail %}
{% load static %}

{% block title %}
    Edit user information
{% endblock %}

{% block content %}
    <div class="container">
            {% include 'user_panel/components/messages.html' %}
            <div class="row">
                <div class="col-md-4" id="dashboardPartial">
                    {% render_partial 'user_panel.views.DashboardViewPartial' %}
                </div>
                <div class="col-md-8">
                <form class="form-floating form-md" action="{% url 'user_panel:edit-info' %}" method="POST" enctype="multipart/form-data">
                    <div class="col-md-4 col-lg-5 col-xl-5 d-flex justify-content-center" style="float: right">
                            <div class="md-form">
                              <div class="file-field">
                                <div class="mb-4">
                                    {% include 'user_panel/components/avatar.html' with user=user %}
                                </div>
                                <div class="d-flex justify-content-center">
                                  <div class="btn btn-mdb-color btn-rounded float-left waves-effect waves-light">
                                    <span>Upload avatar</span>
                                      <span style="float: right">{{ form.avatar }}</span>
                                  </div>
                                </div>
                              </div>
                            </div>

                          </div>
                    <div class="container-fluid">
                        {% csrf_token %}
                        {{ form.username.label }}
                        <div class="mb-3">
                            {{ form.username }}
                        </div>
                        {{ form.first_name.label }}

                        <div class="mb-3">
                            {{ form.first_name }}
                        </div>
                        {{ form.last_name.label }}

                        <div class="mb-3">
                            {{ form.last_name }}
                        </div>

                        {% if form.errors %}
                            <ul>
                                <li class="alert alert-danger">{{ form.errors }}</li>
                            </ul>
                        {% endif %}
                        <button type="submit" class="btn btn-primary">Edit Information</button>
                        <div class="contact-mf"></div>
                </form>
            </div>
    </div>
    </div>
{% endblock %}