PersonalBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    # apps urls
    path('accounts/', include('user_accounts.urls')),
    path('user-panel/', include('user_panel.urls')),
    path('posts/', include('post.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
    # django and third-party app urls
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index_page'),
    path('', views.HomePageView.as_view(), name='contact-form-view'),
]

user_accounts/urls.py
from django.urls import path
from .views import RegisterFormView, LoginFormView, LogoutView,ActivateView, ForgetPasswordView, ResetPasswordView


app_name = 'account'
urlpatterns = [
    path('register', RegisterFormView.as_view(), name='register'),
    path('login', LoginFormView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('activate-account/<activation_code>', ActivateView.as_view(), name='activation_code'),
    path('forgot-password', ForgetPasswordView.as_view(), name='forgot-password'),
    path('reset-password/<activation_code>', ResetPasswordView.as_view(), name='reset_password'),

]

user_panel/urls.py
from django.urls import path
from .views import DashboardView, EditProfileView, ChangePasswordView

app_name = "user_panel"
urlpatterns = [
    path('dashbord', DashboardView.as_view(), name="dashboard"),
    path('change-password', ChangePasswordView.as_view(), name="change-password"),
    path('edit-info', EditProfileView.as_view(), name="edit-info"),
]

templates/main/components/footer_component.html
  <!-- ======= Footer ======= -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="copyright-box">
            <p class="copyright">&copy; Copyright <strong>DevFolio</strong>. All Rights Reserved</p>
            <div class="credits">
              <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=DevFolio
            -->
              Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- End  Footer -->

templates/main/components/header_component.html
{% load static %}
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

{#      <h1 class="logo"><a href="posts_list.html">DevFolio</a></h1>#}
      <!-- Uncomment below if you prefer to use an image logo -->
      <a href="{% url 'home:index_page' %}" class="logo"><img src="{{ settings.logo.url }}" alt="" class="img-fluid"></a>
        <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'home:index_page' %}#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'home:index_page' %}#about">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'home:index_page' %}#services">Services</a></li>
          <li><a class="nav-link scrollto " href="{% url 'home:index_page' %}#blog">Blog</a></li>
            {% if request.user.is_authenticated %}
          <li><a class="nav-link scrollto " href="{% url 'user_panel:dashboard' %}">Dashboard</a></li>
          <li><a class="nav-link scrollto " href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
          <li><a class="nav-link scrollto " href="{% url 'account:register' %}">Register</a></li>
          <li><a class="nav-link scrollto " href="{% url 'account:login' %}">Login</a></li>
            {% endif %}
          <li><a class="nav-link scrollto" href="{% url 'home:index_page' %}#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
      <!-- .navbar -->

    </div>
  </header><!-- End Header -->

templates/main/components/hero_component.html
{% load static %}
<!-- ======= Hero Section ======= -->
  <div id="hero" class="hero route bg-image" style="background-image: url({{ bg_image.url }})">
    <div class="overlay-itro"></div>
    <div class="hero-content display-table">
      <div class="table-cell">
        <div class="container">
            <h1 class="hero-title mb-4">I Am <i class="fst-italic">"{{ name }}"</i></h1>
          <p class="hero-subtitle"><span class="typed" data-typed-items="{% for skill in skills.all %}{{ skill }},{% endfor %}"></span></p>
          <p class="pt-3"><a class="btn btn-primary btn js-scroll px-4" href="{% url 'home:index_page' %}#about" role="button">Learn More</a></p>
        </div>
      </div>
    </div>
  </div>
<!-- End Hero Section -->

templates/main/components/meta_tags_components.html
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">

{% if seo.isMain %}
    <meta  name="description" content="{{ seo.description }}">
    <meta name="keywords" content="{% for seo_keywords in seo.keywords_connection.all %}{{ seo_keywords }},{% endfor %}" >
{% endif %}