PersonalBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    # apps urls
    path('accounts/', include('user_accounts.urls')),
    path('user-panel/', include('user_panel.urls')),
    path('posts/', include('post.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
    # django and third-party app urls
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index_page'),
    path('', views.HomePageView.as_view(), name='contact-form-view'),
]

user_accounts/urls.py
from django.urls import path
from .views import RegisterFormView, LoginFormView, LogoutView,ActivateView, ForgetPasswordView, ResetPasswordView


app_name = 'account'
urlpatterns = [
    path('register', RegisterFormView.as_view(), name='register'),
    path('login', LoginFormView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('activate-account/<activation_code>', ActivateView.as_view(), name='activation_code'),
    path('forgot-password', ForgetPasswordView.as_view(), name='forgot-password'),
    path('reset-password/<activation_code>', ResetPasswordView.as_view(), name='reset_password'),

]

user_accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, verbose_name='Avatar')
    email_verification_code = models.CharField(max_length=100, verbose_name='Email Verification Code')

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

user_accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core import validators


class RegisterForm(forms.Form):
    username = forms.CharField(
        label="Username",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control-lg",
                "id": "username",
                "placeholder": "Your Username",
            }
        ),
        validators=[validators.MaxLengthValidator(50)]
    )
    email = forms.CharField(
        label="Email Address",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "type": "email",
                "class": "form-control-lg",
                "id": "email",
                "placeholder": "Your Email Address",
            },
        ),
        validators=[
            validators.EmailValidator,
            validators.MaxLengthValidator(100)
        ]
    )

    password = forms.CharField(
        label="Password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "id": "password",
            "placeholder": "Your Password", }
        ),
        validators=[
            validators.MinLengthValidator(8),
        ]
    )

    confirm_password = forms.CharField(
        label="Confirm Password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "id": "confirm_password",
            "placeholder": "Confirm Your Password",
        }
        ),
        validators=[
            validators.MinLengthValidator(8),
        ]
    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password == confirm_password:
            return confirm_password
        raise ValidationError('Passwords dont match')


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Username",
        label_suffix="",
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "class": "form-control-lg",
                "id": "username",
                "placeholder": "Your Username",
            }
        ),
    )

    password = forms.CharField(
        label="Password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "id": "password",
            "placeholder": "Your Password", }
        ),
    )


class ForgetPasswordForm(forms.Form):
    username = forms.CharField(
        label="Username",
        label_suffix="",
        widget=forms.TextInput(
            attrs={"type": "text",
                   "class": "form-control-lg",
                   "id": "username",
                   "placeholder": "Your Username",
                   }
        ),
    )


class ResetPasswordForm(forms.Form):
    password = forms.CharField(
        label="Password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "id": "password",
            "placeholder": "Your Password", }
        ),
        validators=[
            validators.MinLengthValidator(8),
        ]
    )

    confirm_password = forms.CharField(
        label="Confirm Password",
        label_suffix="",
        widget=forms.PasswordInput(attrs={
            "type": "password",
            "class": "form-control-lg",
            "id": "confirm_password",
            "placeholder": "Confirm Your Password",
        }
        ),
        validators=[
            validators.MinLengthValidator(8),
        ]
    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password == confirm_password:
            return confirm_password
        raise ValidationError("Password's don't match")

user_accounts/views.py
from django.contrib.auth import login, logout
from django.contrib import messages
from django.http import Http404, HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic.edit import View
from django.utils.crypto import get_random_string
from user_accounts.models import User
from user_accounts.forms import RegisterForm, LoginForm, ForgetPasswordForm, ResetPasswordForm
from tools.send_email_tool import send_email


class RegisterFormView(View):
    def get(self, request):
        register_form = RegisterForm()
        context = {
            'form': register_form
        }
        return render(request, 'user_accounts/register_form.html', context)

    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            print(register_form.cleaned_data)

            user_name, user_email, user_password = register_form.cleaned_data.get(
                'username'), register_form.cleaned_data.get('email'), register_form.cleaned_data.get('password')

            exist_email_user: bool = User.objects.filter(email__iexact=user_email).exists()
            exist_username_user: bool = User.objects.filter(username__iexact=user_name).exists()
            if exist_email_user:
                register_form.add_error('email', f'{user_email} is already taken.')
            elif exist_username_user:
                register_form.add_error('username', f'{user_name} is already taken.')
            else:
                new_user = User(username=user_name, email=user_email, email_verification_code=get_random_string(72),
                                is_active=False)
                new_user.set_password(user_password)
                new_user.save()
                send_email(
                    subject="User activation link",
                    to=new_user.email,
                    context={'user': new_user},
                    template_name='mail_templates/account_activation.html'
                )
                messages.info(self.request,
                              f"An email containing the activation link has been sent to {new_user.email}")
                return redirect(reverse('account:login'))
        context = {
            "form": register_form
        }
        return render(request, 'user_accounts/register_form.html', context)


class LoginFormView(View):
    def get(self, request):
        login_form = LoginForm()
        context = {
            'form': login_form
        }
        return render(request, 'user_accounts/login_form.html', context)

    def post(self, request: HttpRequest):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_name, password = login_form.cleaned_data.get('username'), login_form.cleaned_data.get('password')
            user: User = User.objects.filter(username__iexact=user_name).first()
            if user is not None:
                if not user.is_active:
                    login_form.add_error('username', 'User not found')
                else:
                    isPassword = user.check_password(password)
                    if isPassword:
                        login(request, user)
                        messages.success(self.request, f"Logged in as {user.username}")
                        return redirect(reverse('home:index_page'))
                    else:
                        login_form.add_error('username', 'User not found')
            else:
                login_form.add_error('username', 'User not found')

        context = {
            'form': login_form
        }

        return render(request, 'user_accounts/login_form.html', context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        messages.info(self.request, "Successfully logged out")
        return redirect(reverse('home:index_page'))


class ActivateView(View):
    def get(self, request, activation_code):
        user: User = User.objects.filter(email_verification_code__iexact=activation_code).first()
        if user is not None:
            if not user.is_active:
                user.email_verification_code = get_random_string(72)
                user.is_active = True
                user.save()
                messages.add_message(self.request, messages.SUCCESS, f"{user.username} is activated.")
                return redirect(reverse('account:login'))
            else:
                messages.add_message(self.request, messages.WARNING, f"{user.username} is already active")
                return redirect(reverse('account:login'))

        raise Http404('Activation code is invalid.')


class ForgetPasswordView(View):
    def get(self, request):
        form = ForgetPasswordForm()
        context = {"form": form}
        return render(request, 'user_accounts/forgot_password.html', context)

    def post(self, request):
        form = ForgetPasswordForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data.get('username')
            user: User = User.objects.filter(username__iexact=user_name).first()
            if user is not None:
                user_email = user.email
                send_email('Password Recovery', user_email, context={'user': user},
                           template_name='mail_templates/forget_password.html')
                messages.info(self.request, "PLease check your email")
        context = {"form": form}
        return render(request, 'user_accounts/forgot_password.html', context)


class ResetPasswordView(View):
    def get(self, request, activation_code):
        user: User = User.objects.filter(email_verification_code__iexact=activation_code).first()
        if user is None:
            return redirect(reverse('account:login'))
        form = ResetPasswordForm()
        context = {
            "user": user,
            "form": form
        }
        return render(request, 'user_accounts/reset_password.html', context)

    def post(self, request, activation_code):
        form = ResetPasswordForm(request.POST)
        user: User = User.objects.filter(email_verification_code__iexact=activation_code).first()
        if user is None:
            messages.warning(self.request, "User not found")
            return redirect(reverse('account:login'))
        if form.is_valid():
            new_password = form.cleaned_data.get('confirm_password')
            user.set_password(new_password)
            user.email_verification_code = get_random_string(72)
            user.is_active = True
            user.save()
            send_email(
                subject="Your password has changed",
                to=user.email,
                context={'user': user},
                template_name='mail_templates/password_changed.html'
            )
            messages.success(self.request, "Password successfully changed.")
            return redirect(reverse('account:login'))
        context = {"form": form}
        return render(request, 'user_accounts/reset_password.html', context)

user_accounts/templates/user_accounts/forgot_password.html
{% extends 'main/_layout.html' %}
{% load static %}
{% block title %} Forgot Password  {% endblock %}
{% block content %}

    <div class="container-fluid">

    <div class="container">
    {% if form.errors %}
    <div class="col-md-6">
        <div class="alert alert-danger" >{{ form.errors }}
    </div>
    {% endif %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %}class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    {% endif %}

        <div class="col-md-6">
            <form class="form-group" action="{% url 'account:forgot-password' %}" method="post">
                    {% csrf_token %}
                    {{ form.username }}
                <div class="col-md-12 text-center">
                            <button type="submit" class="button button-a button-big button-rouded">Forgot Password</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

user_accounts/templates/user_accounts/login_form.html
{% extends 'main/_layout.html' %}
{% load static %}
{% block title %} Login  {% endblock %}
{% block content %}

    <div class="container-fluid">

    <div class="container">
    {% if form.errors %}
    <div class="col-md-6">
        <div class="alert alert-danger" >{{ form.errors }}
    </div>
    {% endif %}
                                  {% if messages %}
                            <ul class="messages">
                                  {% for message in messages %}
                                        <li {% if message.tags %}class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
                                  {% endfor %}
                              {% endif %}


        <div class="col-md-6">
            <form class="form-group" action="" method="post">
                    {% csrf_token %}
                {{ form.username }}
                {{ form.password }}
                <p><a  class="password-reset-link" href="{% url 'account:forgot-password' %}">Forgot password?!</a></p>
                <div class="col-md-12 text-center">
                            <button type="submit" class="button button-a button-big button-rouded">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

user_accounts/templates/user_accounts/register_form.html
{% extends 'main/_layout.html' %}
{% load static %}
{% block title %} Register  {% endblock %}
{% block content %}

    <div class="container-fluid">

    <div class="container">
    {% if form.errors %}
    <div class="col-md-6">
        <div class="alert alert-danger" >{{ form.errors }}
    </div>
    {% endif %}
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %}class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}

        <div class="col-md-4">
            <form class="form-group"  action="{% url 'account:register' %}" method="post">
                    {% csrf_token %}
                    {{ form.username }}
                    {{ form.email }}
                    {{ form.password }}
                    {{ form.confirm_password }}
                <div class="col-md-12 text-center">
                            <button type="submit" class="button button-a button-big button-rouded">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

user_accounts/templates/user_accounts/reset_password.html
{% extends 'main/_layout.html' %}
{% load static %}
{% block title %} Reset Password  {% endblock %}
{% block content %}

    <div class="container-fluid">

    <div class="container">
    {% if form.errors %}
    <div class="col-md-6">
        <div class="alert alert-danger" >{{ form.errors }}
    </div>
    {% endif %}
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %}class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}

        <div class="col-md-6">
            <form class="form-group" action="{% url 'account:reset_password' activation_code=user.email_verification_code %}" method="post">
                    {% csrf_token %}
                    {{ form.password }}
                    {{ form.confirm_password }}
                <div class="col-md-12 text-center">
                            <button type="submit" class="button button-a button-big button-rouded">Forgot Password</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}