PersonalBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    # apps urls
    path('accounts/', include('user_accounts.urls')),
    path('user-panel/', include('user_panel.urls')),
    path('posts/', include('post.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
    # django and third-party app urls
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    # add root static files
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index_page'),
    path('', views.HomePageView.as_view(), name='contact-form-view'),
]

user_accounts/urls.py
from django.urls import path
from .views import RegisterFormView, LoginFormView, LogoutView,ActivateView, ForgetPasswordView, ResetPasswordView


app_name = 'account'
urlpatterns = [
    path('register', RegisterFormView.as_view(), name='register'),
    path('login', LoginFormView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('activate-account/<activation_code>', ActivateView.as_view(), name='activation_code'),
    path('forgot-password', ForgetPasswordView.as_view(), name='forgot-password'),
    path('reset-password/<activation_code>', ResetPasswordView.as_view(), name='reset_password'),

]

templates/mail_templates/account_activation.html
{% load today %}
<div class="container">
    <h1>
        Activation link for {{ user.username }}
    </h1>
    <hr>
    <p>
        In order to activate your account click the link below
    </p>
    <p>
        Date: {% return_today %}
    </p>

    <a href="http://localhost:8000{% url 'account:activation_code' activation_code=user.email_verification_code %}">
        Activate
    </a>
</div>

templates/mail_templates/forget_password.html
{% load today %}
<div class="container">
    <h1>
        Password recovery for {{ user.username }}
    </h1>
    <hr>
    <p>
        In order to recover your password click the link below
    </p>
    <p>
        Date: {% return_today %}
    </p>
    <a href="http://localhost:8000{% url 'account:reset_password' activation_code=user.email_verification_code %}">
        Reset Password
    </a>
</div>

templates/mail_templates/password_changed.html
{% load today %}
<div class="container">
    <h1>
        Your password has been changed
    </h1>
    <hr>
    <p>
        Password for {{ user.username }} has been changed successfully.
        Date: {% return_today %}
    </p>
</div>